name: S3 Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - bazzite-deck-9070
        major_version: [41]
    steps:
      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          # aws key id
          aws_key_id: ${{vars.AWS_ACCESS_KEY}}
          # aws secret access key
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          # aws bucket name
          aws_bucket: jersmart-bazzite-isos
          # directory to upload
          source_dir: ${{ steps.upload-directory.outputs.iso-upload-dir }}
          # destination directory for upload
          destination_dir: bazzite-deck-9070
