name: S3 Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      # - name: Upload S3
      #   # You may pin to the exact commit or the version.
      #   # uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e
      #   uses: shallwefootball/upload-s3-action@v1.3.3
      #   with:
      #     # aws key id
      #     aws_key_id: ${{vars.AWS_ACCESS_KEY}}
      #     # aws secret access key
      #     aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     # aws bucket name
      #     aws_bucket: jersmart-bazzite-isos
      #     # directory to upload
      #     source_dir: ${{ github.workspace }}/installer/lorax_templates
      #     # destination directory for upload
      #     destination_dir: bazzite-deck-9070
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: aws s3 cp ${{ github.workspace }}/installer/lorax_templates s3://jersmart-bazzite-isos/bazzite-deck-9070 --recursive
